[package]
name = "vision"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
itertools = "0.13.0"
nalgebra = "0.33"
opencv = "0.93.3"
candle-core = "0.7.2"
candle-nn = "0.7.2"
candle-onnx = "0.7.2"
rayon = "1.10.0"
log = "0.4.22"
